### ISSUE TITLE
How to call from an web application

### ISSUE THREAD

**Issue by tukao89** [linguanostra/Kakasi.NET#1]
Hi, i've try to call kakasi.NET from web app, but not success, it make pool stop, can you help me?

**Comment by linguanostra** [comment]
Hi,

I've just tried it with an ASP.NET MVC application and it doesn't work, the
web host process / application pool will indeed quit as soon as
the KakasiLib.Init() is invoked.

I got it working with a few tweaks, I've also updated the code on GitHub
with a sample web application. I fixed an issue with loading the native
library as well.

You will need to do this also:

The native libkakasi.dll library will look for these 2 dictionary files:

itaijidict
kanwadict

When running as a web application, the search path used by the library will
be the same as the running host process (e.g: iisexpress.exe, w3wp.exe) and
not the path of the running web application.

If it can't find any one of these file, the library will exit the running
process, which is far from ideal.

It's possible to set 2 environment variables that the native library will
use instead of the executing path.

KANWADICTPATH for the full path to the dictionary file: kanwadict
ITAIJIDICTPATH for the full path to the dictionary file: itaijidict

Make sure these variables are set in the running host process otherwise it
won't work and any call to the native library will kill the running process.

The native library doesn't provide any other way to set the path for the
dictionary files.

Make sure you also restart Visual Studio after you set the environment
variables in Windows if you use IIS Express. For IIS, restarting the pool
should do the trick to reload the system environment variables.

I hope you can get it to work.

Regards,

Patrick

**Comment by tukao89** [comment]
Hi,
Many thanks for your help. It's work perfect!!!

**Comment by tukao89** [comment]
My demo page 💃 http://furigana.dekiru.vn/ , i use this to generate furigana :)

**Comment by linguanostra** [comment]
Very nice, well done!
